spring:
  data:
    redis:
      host: 124.71.32.241
      port: 6379
      password: Hit_dreamer123_redis_complex_upup
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Hit_dreamer123_redis_complex_upup
    username: root
    url: jdbc:mysql://124.71.32.241:3306/chatserver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    hit.dreamer: debug

